packages:
  # Shared packages
  - 'pti-calendar-shared-types'
  - 'pti-calendar-shared-utils'
  - 'pti-calendar-api-client'
  - 'pti-calendar-design-system'

  # Backend services (user-service uses npm, excluded from pnpm workspace)
  # - 'pti-calendar-user-service'
  - 'pti-calendar-planning-service'
  - 'pti-calendar-rdv-service'
  - 'pti-calendar-payment-service'
  - 'pti-calendar-notification-service'
  - 'pti-calendar-admin-service'
  - 'pti-calendar-audit-service'

  # Frontend applications
  - 'pti-calendar-client-pwa'
  - 'pti-calendar-pro-webapp'
  - 'pti-calendar-admin-webapp'
  - 'pti-calendar-callcenter-webapp'
